apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-uploads-pv
spec:
  capacity: { storage: 2Gi }
  accessModes: [ReadWriteMany]        # NFS → partagé multi-nœuds par les 3 pods WP
  nfs:
    server: 192.168.252.8
    path: /srv/nfs/wp-uploads
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-uploads-pvc
spec:
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 2Gi } }
  storageClassName: ""
  volumeName: wp-uploads-pv
